### ISSUE TITLE
ERR_INTERNET_DISCONNECTED

### ISSUE THREAD

**Issue by bthorup** [SKAARHOJ/skaarhoj-updater-releases#1]
Got the following message after reboot of Mac.

Background Issue: ```
Error: net::ERR_INTERNET_DISCONNECTED
```

---

SKAARHOJUpdaterBeta 0.9.12
Electron 6.0.12
darwin 18.7.0
Locale: da

**Comment by s00500** [comment]
This should be fixed now in Beta 13, reopen if it comes up again
