### ISSUE TITLE
Correct message when internet is unavailable

### ISSUE THREAD

**Issue by pjnr1** [SKAARHOJ/skaarhoj-updater-releases#10]
When launching the firmware update, without internet connection I get the following error message:
![Skærmbillede 2020-08-10 kl  11 26 57](https://user-images.githubusercontent.com/20884533/89769076-dc3fbd80-dafc-11ea-96dc-a5c4e85a5440.png)

Same goes if checking for updates later on (they program starts normally after clicking okay.)

Seems that the server name for auto-updates isn't resolved. Should have a better error name since it's probably not that uncommon.

**Comment by s00500** [comment]
Pretty strange as I have patched this issue in a previous release, what version are you using ?

**Comment by pjnr1** [comment]
<img width="279" alt="Skærmbillede 2020-08-24 kl  17 07 28" src="https://user-images.githubusercontent.com/20884533/91061299-4c396200-e62c-11ea-8425-e9298048d246.png">

**Comment by s00500** [comment]
Thanks, I have fixed the issue, it will be included in the next release

**Comment by pjnr1** [comment]
Fantastic, thanks :)
