### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dsnoble** [SKAARHOJ/skaarhoj-updater-releases#15]
Background Issue: 
      
```
Error: Object has been destroyed
    at Object.uploadDUE (/Applications/SKAARHOJUpdater.app/Contents/Resources/app.asar/background.js:2:658626)
```

---

SKAARHOJUpdater 1.0.8
Electron 6.1.10
darwin 20.5.0
Locale: en-US

**Comment by s00500** [comment]
Hey @dsnoble, sorry for the long response time, this one slipped through, did you get this again ? does it happen regulary ? do you have any info on how to reproduce this ?
