### ISSUE TITLE
COM4 error

### ISSUE THREAD

**Issue by buckles19** [SKAARHOJ/skaarhoj-updater-releases#29]
Background Issue: 
      
```
Error: Opening COM4: Access denied
```

---

SKAARHOJUpdater 1.0.12
Electron 6.1.10
win32 10.0.19042
Locale: en-US

**Comment by s00500** [comment]
Hi @buckles19,
Do you have any more information for us ? did you try to restart the updater / reconnect the controller when the issue happened ?

**Comment by buckles19** [comment]
I have tried reconnecting the controller, and even tried using the updater on a different device, but it still refuses to recognize the PTZ Extreme that I am trying to connect.

**Comment by s00500** [comment]
Hi @buckles19,
Our support team has a standard procedure for this case, 
Basically it goes like this:

open online configuration, 
go to Firmwareoverview,
generate a new Firmware and download the file
finally use the "Options->Load Firmware From File" menu command to upload the file to the controller

If this does not work or you still have more questions
please contact support@skaarhoj.com to get more detailed help

Greetings,
Lukas
