### ISSUE TITLE
Accessing BluePill Configure

### ISSUE THREAD

**Issue by Prismeo-Jan** [SKAARHOJ/skaarhoj-updater-releases#34]
Background Issue: 
      
```
Error: Invalid URL
    at IpcMainImpl.<anonymous> (/Applications/SKAARHOJUpdater.app/Contents/Resources/app.asar/background.js:2:566053)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
```

---

SKAARHOJUpdater 1.0.14
Electron 16.0.7
darwin 22.4.0
Locale: de

**Comment by Prismeo-Jan** [comment]
Error when trying to open configure from Skaarhoj Updater v1.0.14

**Comment by s00500** [comment]
Hello @Prismeo-Jan, 
which button did you click exactly ?

**Comment by hiddehs** [comment]
I think @Prismeo-Jan is referring to the Configure button of a simulated device in the Updater software.
After clicking on configure I get a similar error message with v1.0.14, in this case I've started the simulator with the following params: `raw-panel-dummies_1.5.1-pre1_darwin_amd64 -panel MINIFLY`

<img width="555" alt="Screenshot 2023-05-18 at 20 21 48" src="https://github.com/SKAARHOJ/skaarhoj-updater-releases/assets/20111194/c0cd0f24-ef71-4da5-b0b0-c2e38dd085e4">

**Comment by s00500** [comment]
Huch ok, interesting edgecase, but I am afraid I will not fix that too soon. But I assume it should not cause other issues meanwhile

**Comment by s00500** [comment]
wontfix for simulated panels
