### ISSUE TITLE
not sure what to do

### ISSUE THREAD

**Issue by SH010101** [SKAARHOJ/skaarhoj-updater-releases#35]
Background Issue: 
      
```
Error: dns service error: bad reference
    at SocketWatcher.MDNSService.self.watcher.callback (C:\Users\steve\AppData\Local\Programs\SKAARHOJUpdater\resources\app.asar\node_modules\mdns\lib\mdns_service.js:18:40)
```

---

SKAARHOJUpdater 1.0.14
Electron 16.0.7
win32 10.0.22621
Locale: en-US

**Comment by s00500** [comment]
Hi @SH010101, have you installed the apple bonjour drivers ?

**Comment by SH010101** [comment]
I have tried.  The last thing I remember about it was it being a  PRINTING component.   Maybe I have the wrong driver.    I honestly haven’t had a chance to work on it again in a while.   I plan to look at it this evening.    Thanks for checking in.   Steven Hollis336.608.8486HollyDogMedia.comOn Aug 21, 2023, at 8:35 AM, Lukas Bachschwell ***@***.***> wrote:﻿
Hi @SH010101, have you installed the apple bonjour drivers ?

**Comment by s00500** [comment]
Ok, so are you trying to get the stuff going, could you use the rest of the updater normally ?

**Comment by s00500** [comment]
stale, closing
