### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by ChristofferThinggaard** [SKAARHOJ/skaarhoj-updater-releases#5]
I have no idea what happened.
I wasn't connected to the internet

Background Issue: 
      
```
Error: net::ERR_INTERNET_DISCONNECTED
```

---

SKAARHOJUpdaterBeta 0.9.19
Electron 6.1.4
win32 10.0.18362
Locale: da

**Comment by s00500** [comment]
This is a duplicate of #1 on windows, closing and keeping track in #1
