### ISSUE TITLE
Check For Updates Error

### ISSUE THREAD

**Issue by MattGrayYes** [SKAARHOJ/skaarhoj-updater-releases#6]
While checking for updates for Rack Fusion Live, popup error keeps appearing:

Background Issue: 
      
```
Error: Object has been destroyed
    at BrowserWindow.setProgressBar (<anonymous>)
    at Bossa.<anonymous> (/Applications/SKAARHOJUpdaterBeta.app/Contents/Resources/app.asar/background.js:37:322050)
    at Bossa.emit (events.js:205:15)
```

---

SKAARHOJUpdaterBeta 0.9.19
Electron 6.1.4
darwin 18.7.0
Locale: en-GB

**Comment by MattGrayYes** [comment]
<img width="702" alt="Screenshot 2020-01-23 at 17 57 40" src="https://user-images.githubusercontent.com/804029/73010201-deb12300-3e09-11ea-948d-3cebab5532af.png">

**Comment by s00500** [comment]
Hey, thanks for reporting, we are looking into it already
duplicate of #4

**Comment by s00500** [comment]
v0.9.20 should fix this issue
Knew Tom Scotts youtube for a long while, now I know yours 👍
Greetings

**Comment by s00500** [comment]
@MattGrayYes Can you confirm this issue is fixed ? Otherwise just reopen here

**Comment by MattGrayYes** [comment]
Yep that’s fixed it for me!
Thanks.
