### ISSUE TITLE
All controller IP config is locked with DHCP enabled

### ISSUE THREAD

**Issue by pjnr1** [SKAARHOJ/skaarhoj-updater-releases#9]
Of course, the IP should be locked to 0.0.0.0, however, Gateway and DNS should still be editable with DHCP enabled.

**Comment by s00500** [comment]
When is that needed ? are gateway and dns not taken from the DHCP config as well ?

**Comment by s00500** [comment]
@pjnr1 ?

**Comment by pjnr1** [comment]
> When is that needed ? are gateway and dns not taken from the DHCP config as well ?

You are probably right; closing the issue
